# Configuration for Harambe with CoM + Posture controller
MainRobot: [json, "@MC_RTC_DIR@/robots/harambe.json"]
Enabled: [HarambeCoMPosture, BaselineWalkingController]
IncludeHalfSitController: false
ControllerModulePaths: ["@BUILD_DIR@/lib/mc_controller"]

ObserverPipelines:
- name: MainPipeline
  observers:
    - type: Encoder
      update: true
      log: true
      position: encoderValues
      velocity: encoderFiniteDifferences

# Logging
Log:
  Policy: threaded
  Directory: /tmp

# GUI Server
GUIServer:
  IPC: /tmp/mc_rtc_gui
  PUB: tcp://*:4252
  REP: tcp://*:4353
